#!/usr/bin/env node
/**
 * generate-docs.js
 *
 * Extracts metadata from Git-Ape agents, skills, workflows, and config files,
 * then generates structured Docusaurus documentation pages.
 *
 * Usage: node scripts/generate-docs.js
 *
 * This script is idempotent — safe to run repeatedly. It overwrites only
 * files marked with the AUTO-GENERATED header.
 */

const fs = require('fs');
const path = require('path');

// Resolve deps from website/node_modules since they're installed there
const WEBSITE_DIR = path.resolve(__dirname, '..', 'website');
const matter = require(path.join(WEBSITE_DIR, 'node_modules', 'gray-matter'));
const yaml = require(path.join(WEBSITE_DIR, 'node_modules', 'js-yaml'));

const ROOT = path.resolve(__dirname, '..');
const DOCS_OUT = path.join(ROOT, 'website', 'docs');
const AGENTS_DIR = path.join(ROOT, '.github', 'agents');
const SKILLS_DIR = path.join(ROOT, '.github', 'skills');
const WORKFLOWS_DIR = path.join(ROOT, '.github', 'workflows');

const AUTO_HEADER = '<!-- AUTO-GENERATED — DO NOT EDIT. Source: {source} -->\n\n';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeAutoGenerated(filePath, source, content) {
  const header = AUTO_HEADER.replace('{source}', source);
  fs.writeFileSync(filePath, header + content, 'utf8');
  console.log(`  ✓ ${path.relative(ROOT, filePath)}`);
}

function readFile(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function toTitleCase(str) {
  return str
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

// ---------------------------------------------------------------------------
// Agent doc generation
// ---------------------------------------------------------------------------

function generateAgentDocs() {
  console.log('\n📦 Generating agent docs...');
  const outDir = path.join(DOCS_OUT, 'agents');
  ensureDir(outDir);

  const agentFiles = fs.readdirSync(AGENTS_DIR).filter((f) => f.endsWith('.agent.md'));
  const agents = [];

  for (const file of agentFiles) {
    const filePath = path.join(AGENTS_DIR, file);
    const raw = readFile(filePath);
    const { data: fm, content: body } = matter(raw);

    const slug = slugify(fm.name || file.replace('.agent.md', ''));
    const name = fm.name || toTitleCase(file.replace('.agent.md', ''));
    const description = fm.description || '';
    const tools = Array.isArray(fm.tools) ? fm.tools : [];
    const model = fm.model || 'Default';
    const userInvocable = fm['user-invocable'] !== false;
    const argumentHint = fm['argument-hint'] || '';
    const subAgents = fm.agents || [];

    agents.push({ name, slug, description, userInvocable, file });

    // Extract meaningful body (skip the frontmatter warning section, keep substance)
    const bodyTrimmed = body.trim();

    let content = `---
title: "${name}"
sidebar_label: "${name}"
description: "${description.replace(/"/g, '\\"')}"
---

# ${name}

> ${description}

## Details

| Property | Value |
|----------|-------|
| **File** | \`.github/agents/${file}\` |
| **User Invocable** | ${userInvocable ? '✅ Yes' : '❌ No (sub-agent only)'} |
| **Model** | ${model} |
${argumentHint ? `| **Argument Hint** | ${argumentHint} |\n` : ''}
## Tools

${tools.length > 0 ? tools.map((t) => `- \`${t}\``).join('\n') : '_No tools specified_'}
`;

    if (subAgents.length > 0) {
      content += `\n## Sub-Agents\n\n${subAgents.map((a) => `- ${a}`).join('\n')}\n`;
    }

    content += `\n## Full Prompt\n\n<details>\n<summary>Click to expand the full agent prompt</summary>\n\n${bodyTrimmed}\n\n</details>\n`;

    writeAutoGenerated(path.join(outDir, `${slug}.md`), `.github/agents/${file}`, content);
  }

  // Generate overview page
  const overviewContent = `---
title: "Agents Overview"
sidebar_label: "Overview"
sidebar_position: 1
description: "Overview of all Git-Ape agents and their orchestration"
---

# Agents Overview

Git-Ape uses a multi-agent architecture where \`@git-ape\` is the central orchestrator that delegates to specialized sub-agents.

## Agent Inventory

| Agent | Description | User Invocable |
|-------|-------------|:--------------:|
${agents.map((a) => `| [${a.name}](./${a.slug}) | ${a.description} | ${a.userInvocable ? '✅' : '❌'} |`).join('\n')}

## Orchestration Architecture

\`\`\`mermaid
graph TD
    GA["<b>@git-ape</b><br/>Main Orchestrator"]

    GA --> DP
    GA --> AD
    GA --> UT

    subgraph DP ["Deployment Pipeline"]
        RG["Requirements Gatherer"]
        TG["Template Generator"]
        SG{{"Security Gate (BLOCKING)"}}
        WR["WAF Review"]
        UC{{"User Confirmation"}}
        RD["Resource Deployer"]
        RG --> TG --> SG --> WR --> UC --> RD
    end

    subgraph AD ["Advisory"]
        PA["Principal Architect"]
        PO["Policy Advisor"]
    end

    subgraph UT ["Utility"]
        IE["IaC Exporter"]
        OB["Git-Ape Onboarding"]
    end
\`\`\`
`;

  writeAutoGenerated(path.join(outDir, 'overview.md'), '.github/agents/', overviewContent);
  return agents;
}

// ---------------------------------------------------------------------------
// Skill doc generation
// ---------------------------------------------------------------------------

function generateSkillDocs() {
  console.log('\n🔧 Generating skill docs...');
  const outDir = path.join(DOCS_OUT, 'skills');
  ensureDir(outDir);

  const skillDirs = fs.readdirSync(SKILLS_DIR).filter((d) => {
    return fs.statSync(path.join(SKILLS_DIR, d)).isDirectory();
  });

  const skills = [];

  for (const dir of skillDirs) {
    const skillMdPath = path.join(SKILLS_DIR, dir, 'SKILL.md');
    if (!fs.existsSync(skillMdPath)) continue;

    const raw = readFile(skillMdPath);
    const { data: fm, content: body } = matter(raw);

    const slug = slugify(fm.name || dir);
    const name = fm.name || dir;
    const description = fm.description || '';
    const userInvocable = fm['user-invocable'] !== false;
    const argumentHint = fm['argument-hint'] || '';

    // Determine phase from skill content/name
    let phase = 'General';
    const preDeploySkills = ['azure-naming-research', 'azure-resource-availability', 'azure-security-analyzer', 'azure-deployment-preflight', 'azure-role-selector', 'azure-cost-estimator', 'prereq-check', 'azure-policy-advisor'];
    const postDeploySkills = ['azure-integration-tester', 'azure-resource-visualizer'];
    const opsSkills = ['azure-drift-detector', 'git-ape-onboarding', 'azure-rest-api-reference'];

    if (preDeploySkills.includes(name)) phase = 'Pre-Deploy';
    else if (postDeploySkills.includes(name)) phase = 'Post-Deploy';
    else if (opsSkills.includes(name)) phase = 'Operations';

    skills.push({ name, slug, description, userInvocable, phase, dir });

    const bodyTrimmed = body.trim();

    let content = `---
title: "${toTitleCase(name)}"
sidebar_label: "${toTitleCase(name)}"
description: "${description.replace(/"/g, '\\"')}"
---

# ${toTitleCase(name)}

> ${description}

## Details

| Property | Value |
|----------|-------|
| **Skill Directory** | \`.github/skills/${dir}/\` |
| **Phase** | ${phase} |
| **User Invocable** | ${userInvocable ? '✅ Yes' : '❌ No'} |
${argumentHint ? `| **Usage** | \`/${name} ${argumentHint}\` |\n` : `| **Usage** | \`/${name}\` |\n`}

## Documentation

${bodyTrimmed}
`;

    writeAutoGenerated(path.join(outDir, `${slug}.md`), `.github/skills/${dir}/SKILL.md`, content);
  }

  // Generate overview page
  const phases = ['Pre-Deploy', 'Post-Deploy', 'Operations', 'General'];
  let overviewContent = `---
title: "Skills Overview"
sidebar_label: "Overview"
sidebar_position: 1
description: "Overview of all Git-Ape skills organized by deployment phase"
---

# Skills Overview

Skills are focused capabilities invoked by agents at specific stages of the deployment workflow. Each skill handles one task.

`;

  for (const phase of phases) {
    const phaseSkills = skills.filter((s) => s.phase === phase);
    if (phaseSkills.length === 0) continue;

    overviewContent += `## ${phase} Skills\n\n| Skill | Description | Invocable |\n|-------|-------------|:---------:|\n`;
    for (const s of phaseSkills) {
      overviewContent += `| [${toTitleCase(s.name)}](./${s.slug}) | ${s.description} | ${s.userInvocable ? '✅' : '❌'} |\n`;
    }
    overviewContent += '\n';
  }

  overviewContent += `## Skill Invocation in Deployment Flow

\`\`\`mermaid
graph LR
    subgraph Pre["Pre-Deploy"]
        S1["/${skills.filter(s => s.phase === 'Pre-Deploy').map(s => s.name).join('\\n/')}"]
    end
    subgraph Post["Post-Deploy"]
        S2["/${skills.filter(s => s.phase === 'Post-Deploy').map(s => s.name).join('\\n/')}"]
    end
    subgraph Ops["Operations"]
        S3["/${skills.filter(s => s.phase === 'Operations').map(s => s.name).join('\\n/')}"]
    end
    Pre --> Post --> Ops
\`\`\`
`;

  writeAutoGenerated(path.join(outDir, 'overview.md'), '.github/skills/', overviewContent);
  return skills;
}

// ---------------------------------------------------------------------------
// Workflow doc generation
// ---------------------------------------------------------------------------

function generateWorkflowDocs() {
  console.log('\n⚙️  Generating workflow docs...');
  const outDir = path.join(DOCS_OUT, 'workflows');
  ensureDir(outDir);

  const workflowFiles = fs.readdirSync(WORKFLOWS_DIR).filter((f) => f.endsWith('.yml') || f.endsWith('.yaml'));
  const workflows = [];

  for (const file of workflowFiles) {
    const filePath = path.join(WORKFLOWS_DIR, file);
    const raw = readFile(filePath);
    let wf;
    try {
      wf = yaml.load(raw);
    } catch (e) {
      console.warn(`  ⚠ Failed to parse ${file}: ${e.message}`);
      continue;
    }

    const name = wf.name || file;
    const slug = slugify(file.replace(/\.ya?ml$/, ''));
    const triggers = wf.on || wf.true || {};
    const jobs = wf.jobs || {};
    const jobNames = Object.keys(jobs);
    const permissions = wf.permissions || {};

    workflows.push({ name, slug, file, triggers, jobNames });

    // Format triggers
    let triggerSection = '';
    if (typeof triggers === 'string') {
      triggerSection = `- \`${triggers}\``;
    } else if (Array.isArray(triggers)) {
      triggerSection = triggers.map((t) => `- \`${t}\``).join('\n');
    } else {
      for (const [event, config] of Object.entries(triggers)) {
        triggerSection += `- **\`${event}\`**`;
        if (config && typeof config === 'object') {
          if (config.branches) triggerSection += ` — branches: \`${JSON.stringify(config.branches)}\``;
          if (config.paths) triggerSection += ` — paths: \`${config.paths.slice(0, 3).join(', ')}${config.paths.length > 3 ? '...' : ''}\``;
          if (config.types) triggerSection += ` — types: \`${config.types.join(', ')}\``;
        }
        triggerSection += '\n';
      }
    }

    // Format jobs
    let jobSection = '';
    for (const [jobId, jobConfig] of Object.entries(jobs)) {
      const jobName = jobConfig.name || jobId;
      const runsOn = jobConfig['runs-on'] || 'unknown';
      const env = jobConfig.environment || '';
      const needs = jobConfig.needs || [];
      const stepCount = (jobConfig.steps || []).length;

      jobSection += `### \`${jobId}\`\n\n`;
      jobSection += `| Property | Value |\n|----------|-------|\n`;
      jobSection += `| **Display Name** | ${jobName} |\n`;
      jobSection += `| **Runs On** | \`${runsOn}\` |\n`;
      if (env) jobSection += `| **Environment** | \`${typeof env === 'string' ? env : env.name || JSON.stringify(env)}\` |\n`;
      if (needs.length > 0) jobSection += `| **Depends On** | ${(Array.isArray(needs) ? needs : [needs]).map(n => `\`${n}\``).join(', ')} |\n`;
      jobSection += `| **Steps** | ${stepCount} |\n\n`;
    }

    const content = `---
title: "${name}"
sidebar_label: "${name.replace('Git-Ape: ', '')}"
description: "GitHub Actions workflow: ${name}"
---

# ${name}

**Workflow file:** \`.github/workflows/${file}\`

## Triggers

${triggerSection}

## Permissions

${Object.keys(permissions).length > 0
  ? Object.entries(permissions).map(([k, v]) => `- \`${k}: ${v}\``).join('\n')
  : '_Inherited from repository defaults_'}

## Jobs

${jobSection}

## Source

<details>
<summary>Click to view full workflow YAML</summary>

\`\`\`yaml
${raw}
\`\`\`

</details>
`;

    writeAutoGenerated(path.join(outDir, `${slug}.md`), `.github/workflows/${file}`, content);
  }

  // Generate overview
  const overviewContent = `---
title: "CI/CD Workflows Overview"
sidebar_label: "Overview"
sidebar_position: 1
description: "Overview of Git-Ape GitHub Actions workflows"
---

# CI/CD Workflows Overview

Git-Ape provides GitHub Actions workflows for automated deployment lifecycle management.

## Workflow Inventory

| Workflow | File | Triggers | Jobs |
|----------|------|----------|------|
${workflows.map((w) => `| [${w.name}](./${w.slug}) | \`${w.file}\` | ${Object.keys(typeof w.triggers === 'object' && !Array.isArray(w.triggers) ? w.triggers : {}).join(', ') || String(w.triggers)} | ${w.jobNames.join(', ')} |`).join('\n')}

## Pipeline Architecture

\`\`\`mermaid
graph LR
    PR["PR Opened"] --> Plan["git-ape-plan.yml<br/>Validate + What-If"]
    Plan --> Review["Human Review"]
    Review --> Merge["Merge to main"]
    Merge --> Deploy["git-ape-deploy.yml<br/>ARM Deployment"]
    Deploy --> Test["Integration Tests"]

    Comment["/deploy Comment"] --> Deploy

    Destroy["PR: status → destroy-requested"] --> DestroyMerge["Merge"]
    DestroyMerge --> DestroyWF["git-ape-destroy.yml<br/>Delete Resources"]

    Manual["Manual Dispatch"] --> Verify["git-ape-verify.yml<br/>Verify Setup"]
\`\`\`
`;

  writeAutoGenerated(path.join(outDir, 'overview.md'), '.github/workflows/', overviewContent);
  return workflows;
}

// ---------------------------------------------------------------------------
// Reference doc generation (plugin.json, marketplace.json)
// ---------------------------------------------------------------------------

function generateReferenceDocs() {
  console.log('\n📋 Generating reference docs...');
  const outDir = path.join(DOCS_OUT, 'reference');
  ensureDir(outDir);

  // plugin.json
  const pluginJsonPath = path.join(ROOT, 'plugin.json');
  if (fs.existsSync(pluginJsonPath)) {
    const pluginJson = JSON.parse(readFile(pluginJsonPath));
    const content = `---
title: "plugin.json Reference"
sidebar_label: "plugin.json"
description: "Git-Ape Copilot CLI plugin manifest"
---

# plugin.json

The plugin manifest defines the Git-Ape Copilot CLI plugin metadata.

## Current Configuration

| Field | Value |
|-------|-------|
| **Name** | ${pluginJson.name} |
| **Version** | ${pluginJson.version} |
| **Description** | ${pluginJson.description} |
| **Author** | ${pluginJson.author?.name || 'N/A'} |
| **License** | ${pluginJson.license || 'N/A'} |
| **Agents Path** | \`${pluginJson.agents}\` |
| **Skills Path** | \`${pluginJson.skills}\` |

## Keywords

${(pluginJson.keywords || []).map((k) => `\`${k}\``).join(' · ')}

## Full Source

\`\`\`json
${JSON.stringify(pluginJson, null, 2)}
\`\`\`
`;
    writeAutoGenerated(path.join(outDir, 'plugin-json.md'), 'plugin.json', content);
  }

  // marketplace.json
  const marketplacePath = path.join(ROOT, '.github', 'plugin', 'marketplace.json');
  if (fs.existsSync(marketplacePath)) {
    const mktJson = JSON.parse(readFile(marketplacePath));
    const content = `---
title: "Marketplace Configuration"
sidebar_label: "Marketplace"
description: "Git-Ape marketplace plugin configuration"
---

# Marketplace Configuration

The marketplace manifest configures how Git-Ape appears in the Copilot CLI plugin marketplace.

## Current Configuration

| Field | Value |
|-------|-------|
| **Name** | ${mktJson.name} |
| **Owner** | ${mktJson.owner?.name || 'N/A'} |
| **Version** | ${mktJson.metadata?.version || 'N/A'} |
| **Description** | ${mktJson.metadata?.description || 'N/A'} |

## Plugins

${(mktJson.plugins || []).map((p) => `- **${p.name}** v${p.version}: ${p.description}`).join('\n')}

## Full Source

\`\`\`json
${JSON.stringify(mktJson, null, 2)}
\`\`\`
`;
    writeAutoGenerated(path.join(outDir, 'marketplace.md'), '.github/plugin/marketplace.json', content);
  }
}

// ---------------------------------------------------------------------------
// Category metadata files
// ---------------------------------------------------------------------------

function generateCategoryFiles() {
  console.log('\n📁 Generating category metadata...');
  const categories = [
    { dir: 'getting-started', label: 'Getting Started', position: 2, collapsed: false },
    { dir: 'agents', label: 'Agents', position: 3, collapsed: false },
    { dir: 'skills', label: 'Skills', position: 4, collapsed: false },
    { dir: 'workflows', label: 'CI/CD Workflows', position: 5 },
    { dir: 'deployment', label: 'Deployment', position: 6 },
    { dir: 'reference', label: 'Reference', position: 7 },
  ];

  for (const cat of categories) {
    const catFile = path.join(DOCS_OUT, cat.dir, '_category_.json');
    const catData = {
      label: cat.label,
      position: cat.position,
      link: { type: 'generated-index', description: `${cat.label} documentation for Git-Ape.` },
    };
    if (cat.collapsed !== undefined) catData.collapsed = cat.collapsed;
    fs.writeFileSync(catFile, JSON.stringify(catData, null, 2) + '\n', 'utf8');
    console.log(`  ✓ ${path.relative(ROOT, catFile)}`);
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  console.log('🚀 Git-Ape Documentation Generator');
  console.log(`   Root: ${ROOT}`);
  console.log(`   Output: ${DOCS_OUT}`);

  ensureDir(DOCS_OUT);

  generateCategoryFiles();
  const agents = generateAgentDocs();
  const skills = generateSkillDocs();
  const workflows = generateWorkflowDocs();
  generateReferenceDocs();

  console.log('\n✅ Documentation generation complete!');
  console.log(`   Agents: ${agents.length}`);
  console.log(`   Skills: ${skills.length}`);
  console.log(`   Workflows: ${workflows.length}`);
}

main();
