import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/azure-setup',
        'getting-started/onboarding',
        'getting-started/codespaces',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      collapsed: false,
      items: [
        'agents/overview',
        {type: 'autogenerated', dirName: 'agents'},
      ],
    },
    {
      type: 'category',
      label: 'Skills',
      collapsed: false,
      items: [
        'skills/overview',
        {type: 'autogenerated', dirName: 'skills'},
      ],
    },
    {
      type: 'category',
      label: 'CI/CD Workflows',
      items: [
        'workflows/overview',
        {type: 'autogenerated', dirName: 'workflows'},
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/state',
        'deployment/drift-detection',
        'deployment/examples',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/plugin-json',
        'reference/marketplace',
        'reference/arm-templates',
      ],
    },
    'changelog',
  ],
};

export default sidebars;
