import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/azure-setup',
        'getting-started/onboarding',
        'getting-started/codespaces',
      ],
    },
    {
      type: 'category',
      label: 'Who Is This For?',
      collapsed: false,
      items: [
        'personas/for-executives',
        'personas/for-engineering-leads',
        'personas/for-devops',
        'personas/for-platform-engineering',
        'personas/for-engineers',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      collapsed: false,
      items: [
        'use-cases/deploy-function-app',
        'use-cases/deploy-web-app-sql',
        'use-cases/deploy-container-app',
        'use-cases/cost-estimation',
        'use-cases/security-analysis',
        'use-cases/waf-review',
        'use-cases/policy-compliance',
        'use-cases/drift-detection',
        'use-cases/import-existing-infra',
        'use-cases/cicd-pipeline',
        'use-cases/multi-environment',
        'use-cases/headless-mode',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      collapsed: false,
      items: [
        'agents/overview',
        {type: 'autogenerated', dirName: 'agents'},
      ],
    },
    {
      type: 'category',
      label: 'Skills',
      collapsed: false,
      items: [
        'skills/overview',
        {type: 'autogenerated', dirName: 'skills'},
      ],
    },
    {
      type: 'category',
      label: 'CI/CD Workflows',
      items: [
        'workflows/overview',
        {type: 'autogenerated', dirName: 'workflows'},
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/state',
        'deployment/drift-detection',
        'deployment/examples',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/plugin-json',
        'reference/marketplace',
        'reference/arm-templates',
      ],
    },
    'changelog',
  ],
};

export default sidebars;
